### ISSUE TITLE
DIF 10: Add HTTPS URL Link Checker

### ISSUE THREAD

**Issue by spa0002** [NASA-IMPACT/pyQuARC#133]
**Is this a new check? Please describe the check and the field.**
</DIF/Summary/Abstract>: checks that links to sites with Hypertext Transfer Protocol Secure extension have 'https' instead of 'http'.

**Describe the checks in steps**
   1. Identify if a URL link exists in the field
   2. Checks to see if the URL has the Hypertext Transfer Protocol Secure extension.
   3. If so, checks if the URL link is 'https' instead of 'http'

**Is there a similar check already implemented? Please list the name of the check**
N/A

**Additional context**
Would apply to any field with URL links.

**Comment by svbagwell** [comment]
fixed in feature/ummg_support branch -- note that a space needs to be before the start of the URL. There wasn't one in the fake metadata file, causing the check to fail
