### ISSUE TITLE
DIF 10: Add Sensor Number Checker

### ISSUE THREAD

**Issue by spa0002** [NASA-IMPACT/pyQuARC#144]
**Is this a new check? Please describe the check and the field.**
</DIF/Platform/Instrument/NumberOfSensors>: checks that the number of sensors listed in this field matches the number of sensor short names present in the metadata.

**Describe the checks in steps**

   1. If field exists, read in the number from the entry in /DIF/Platform/Instrument/NumberOfSensors
   2. Check that sensor short names exist and count the number present in the metadata
   3. Check that the number entry matches the number of sensor short names listed in metadata

**Is there a similar check already implemented? Please list the name of the check**
n/a

**Additional context**
n/a

**Comment by slesaad** [comment]
/DIF/Platform/Instrument/Sensor/Name

**Comment by svbagwell** [comment]
This check exists in rule_mapping.json, but I don't see it in checks.json, or check.messages.json
I also didn't see a function in custom_validator.py
