### ISSUE TITLE
DIF10: Add GCMD check for /DIF/Temporal_Coverage/Paleo_DateTime/Chronostratigraphic_Unit/Eon

### ISSUE THREAD

**Issue by svbagwell** [NASA-IMPACT/pyQuARC#146]
**Is this a new check? Please describe the check and the field.**
</DIF/Temporal_Coverage/Paleo_DateTime/Chronostratigraphic_Unit/Eon>: Ensure that the provided term complies with the GCMD

**Describe the checks in steps**
1. Check to see if there is a term provided for /DIF/Temporal_Coverage/Paleo_DateTime/Chronostratigraphic_Unit/Eon
2. If one is provided, ensure it exists in the GCMD list "CHRONO_UNITS" in the "Eon" column.
3. If it does not exist in the list, provide the following error message: "<term> does not adhere to the GCMD." 

**Is there a similar check already implemented? Please list the name of the check**
Instrument Short Name GCMD Check

**Additional context**
N/A

**Comment by spa0002** [comment]
"Runs as expected
Hierarchy is checked"
