### ISSUE TITLE
No such file or directory pyQuARC/version.txt 

### ISSUE THREAD

**Issue by cgokey** [NASA-IMPACT/pyQuARC#161]
**Describe the bug**
After installing pyQuARC as a package to a local directory, we are trying import that package and get a No such file or directory pyQuARC/version.txt.   Note: We are not in the pyQuARC directory, we are importing the package from a different location.   This also happens if we install pyQuARC globally as well.

**To Reproduce**

```
>>> from pyQuARC import ARC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cgokey/Developer/rails/cmr-metadata-review/lib/./pyQuARC-1.1.0-py3.9.egg/pyQuARC/__init__.py", line 13, in <module>
    with open("pyQuARC/version.txt") as version_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pyQuARC/version.txt'
```

**Expected behavior**
It should be able to import without errors.

**Comment by xhagrg** [comment]
#159 fixes it.
