### ISSUE TITLE
GCMD Platform Keywords need to be updated

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#184]
**Describe the bug**
The GCMD Platform Keywords were updated recently. pyQuARC is currently using the older version which causes errors that aren't valid.

**To Reproduce**
1. On the umm_g support branch, change the platform type to "Propeller" in the dif10 test file
2. Run pyQuARC
3. See error "Error: The provided platform type `Propeller` does not comply with the GCMD. Please submit a request to support@earthdata.nasa.gov to have this platform type added to the GCMD Platforms KMS."

**Expected behavior**
No error expected since this is a valid platform type

**Outputs**
Error: The provided platform type `Propeller` does not comply with the GCMD. Please submit a request to support@earthdata.nasa.gov to have this platform type added to the GCMD Platforms KMS.

**Additional context**
GCMD Platform Keywords were recently updated.

**Comment by slesaad** [comment]
We already have this category, but it wasn't working because the GCMD url changed from `gcmdservices.gsfc.nasa.gov` to `gcmd.earthdata.nasa.gov`. Fixed in an upcoming PR.
