### ISSUE TITLE
DIF10: The iso_topic_category_check produces invalid error.

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#185]
**Describe the bug**
The iso_topic_category_check with associated field "DIF/ISO_Topic_Category" produces an error even though the provided value is in the controlled vocabulary list.

**To Reproduce**
1. Run the program for C1945170198-LARC_ASDC using dif10 format. Note: the provided value is "IMAGERY/BASE MAPS/EARTH COVER".
2. See error: "Error: Invalid ISO Topic Category. Provide a valid ISO Topic Category value from the following list: ['BIOTA', 'BOUNDARIES', 'CLIMATOLOGY/METEOROLOGY/ATMOSPHERE', 'DISASTER', 'ECONOMY', 'ELEVATION', 'ENVIRONMENT', 'EXTRA TERRESTRIAL', 'FARMING', 'GEOSCIENTIFIC INFORMATION', 'HEALTH', 'IMAGERY/BASE MAPS/EARTH COVER', 'INLAND WATERS', 'INTELLIGENCE/MILITARY', 'LOCATION', 'OCEANS', 'PLANNING CADASTRE', 'SOCIETY', 'STRUCTURE', 'TRANSPORTATION', 'UTILITIES/COMMUNICATIONS']."

**Expected behavior**
No error expected since the provided value is in the controlled vocab list.

**Comment by jenny-m-wood** [comment]
@slesaad @xhagrg Update on this - this is still an issue. Our team is not sure how to resolve it.

**Comment by slesaad** [comment]
This should solve multiple errors, not just `iso_topic_category_check`. PR: #226

**Comment by slesaad** [comment]
closed by #226
