### ISSUE TITLE
validate_ending_datetime_against_granules failed

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#220]
**Describe the bug**
The "validate_ending_datetime_against_granules" check failed producing a pyQuARC error: 

"ERROR: Running check for the rule: 'validate_ending_datetime_against_granules' failed.. Details: validate_ending_datetime_against_granules() missing 1 required positional argument: 'version'"

**To Reproduce**
1. Run the command: "python3 main.py --concept_ids C2119341690-LARC_ASDC --format umm-c"
2. See error

**Expected behavior**
I did not expect this check to fail since a version is provided in the metadata for this collection.

**Outputs**
This error exists for a number of records (e.g. C2081904030-LARC_ASDC, C1997469361-LARC_ASDC). It seems like it may be a UMM-C specific error since it was not present in any of the tested dif10 records.

**Additional context**

**Comment by slesaad** [comment]
closed by #225
