### ISSUE TITLE
Standard Product Check errors

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#261]
**Describe the bug**
If a standard product flag is provided as false in a UMM-C record, pyQuARC still produces an error stating that the flag is missing.

**To Reproduce**
1. Run pyQuARC on sample UMM-C record (C1577484501-LARC_ASDC)
2. See error even though metadata indicates a value of "false" as the Standard Product flag

**Expected behavior**
No error should show when a value is provided in the Standard Product field.

**Comment by smk0033** [comment]
Merged and released - closing
