### ISSUE TITLE
Potentially Modify Beginning/Ending Date Time checks

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#262]
**Existing checks that could potentially be modified**
Checks: validate_beginning_datetime_against_granules and validate_ending_datetime_against_granules

**Current Performance**
Currently, these checks look for an exact match between what's shown in the collection datetime fields and the granule datetime fields. Sometimes the time is the same, apart from extra zeros at the end. 

**Suggested Modifications**
Modify the check so that it validates to the same level of precision as an ARC team member. 

**Example Records**
C2068391958-LARC_ASDC (umm-c)
C1626189760-LARC (echo-c)

**Comment by smk0033** [comment]
Merged and released - closing
