### ISSUE TITLE
doi_link_update check errors for DIF10 and ECHO-C

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#263]
**Describe the bug**
For echo-c and dif10 schemas, the doi_link_update check is not working correctly. It causes pyQuARC to quit instead of producing an output message.

**To Reproduce**
1. Run pyQuARC for sample echo-c record (C1411142649-LARC)
2. See error

**Expected behavior**
Expected pyQuARC to provide summary output instead of quitting.

**Comment by smk0033** [comment]
Merged and seems to be fixed
