### ISSUE TITLE
ISO standard check not working for sample record

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#266]
**Describe the bug**
For G184443593-LARC, the date times appear to be provided correctly (i.e. in the standard ISO format). pyQuARC displays an error that they are not provided in ISO format.

**To Reproduce**
1. Run pyQuARC for G184443593-LARC (echo-g)
2. See error

**Expected behavior**
Expected not to see this error since information was provided correctly.

**Additional context**
Associated collection: C179031451-LARC (echo-c)

**Comment by smk0033** [comment]
Merged and seems to be fixed
