### ISSUE TITLE
Add pyQuARC version number to the QuARC API endpoint

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#281]
To help with pyQuARC-Dashboard integration, the CMR Dashboard team has asked for the version number to be added to the current QuARC API endpoint (https://quarc.nasa-impact.net/docs/#/default/post_validate)

**Comment by tbs1979** [comment]
This blocks a ticket https://bugs.earthdata.nasa.gov/browse/CMRARC-799 on our end: The PyQuARC version is not being displayed in the Dashboard footer; instead it shows as "UNKNOWN"

**Comment by xhagrg** [comment]
@tbs1979 the changes have been deployed. You should be able to get the versions of the quarc and pyquarc via https://quarc.nasa-impact.net/version

**Comment by smk0033** [comment]
Updated on our end and version number also appears in dashboard - closing
