### ISSUE TITLE
Add Sensor Short Name GCMD check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#41]
**Is this a new check? Please describe the check and the field.**
<Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/ShortName>: check that the provided sensor short name is listed in the Instrument GCMD list under the Short Name column.

**Describe the checks in steps**
1. Check that Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/ShortName is included in the 'Instruments' GCMD list, 'Short_Name' column.
2. If it isn't, produce a message that states: "The provided sensor short name is not a valid GCMD keyword."

**Is there a similar check already implemented? Please list the name of the check**
Other GCMD checks are similar (i.e. science keywords, instrument names, etc.)

**Additional context**

**Comment by slesaad** [comment]
We already have a `instrument_short_name_gcmd_check` , just added this field to the `rule_mapping` file
```
"instrument_short_name_gcmd_check": {
        "rule_name": "Instrument Shortname GCMD Check",
        "fields_to_apply": [
            {
                "fields": [
                    "Collection/Platforms/Platform/Instruments/Instrument/ShortName"
                ]
            },
            {
                "fields": [
                    "Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/ShortName"
                ]
            }
        ],
        "severity": "error"
    },
```

**Comment by slesaad** [comment]
![Screen Shot 2021-04-27 at 11 44 13](https://user-images.githubusercontent.com/7830949/116280031-e4ed2800-a74d-11eb-8753-60afbc44ba46.png)
