### ISSUE TITLE
Add Sensor Long Name GCMD check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#42]
**Is this a new check? Please describe the check and the field.**
<Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/LongName>: check that the provided sensor long name is listed in the Instrument GCMD list under the Long Name column.

**Describe the checks in steps**
Check that Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/LongName is included in the 'Instruments' GCMD list, 'Long_Name' column.
If it isn't, produce a message that states: "The provided sensor long name is not a valid GCMD keyword."

**Is there a similar check already implemented? Please list the name of the check**
Other GCMD checks are similar (i.e. science keywords, instrument names, etc.)

**Additional context**
'Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/LongName' is dependent on the 'Collection/Platforms/Platform/Instruments/Instrument/Sensors/Sensor/ShortName'. The long name should be in the same hierarchy as the short name (i.e. similar to the science keyword hierarchies)

**Comment by slesaad** [comment]
Added field to already existing check in `rule_mapping`.
Works as expected:

![Screen Shot 2021-04-27 at 11 53 24](https://user-images.githubusercontent.com/7830949/116281283-2cc07f00-a74f-11eb-8790-288b4cadb721.png)
