### ISSUE TITLE
Add Project Date Logic Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#45]
**Is this a new check? Please describe the check and the field.**
<Collection/Campaigns/Campaign/StartDate> and <Collection/Campaigns/Campaign/EndDate>: check to ensure the Campaign Start Date is before the Campaign End Date.

**Describe the checks in steps**
1. Check to ensure the Campaign Start Date is before the Campaign End Date.
2. If it isn't, provide an error message stating "The Campaign Start Date comes after the Campaign End Date."
3. If they are the same date, provide a warning that states, "The Campaign Start Date and End Date are the same."

**Is there a similar check already implemented? Please list the name of the check**
Range Date Time Logic Check

**Additional context**
For additional information, please see the Project Date Logic Check in the QA Rules spreadsheet.

**Comment by slesaad** [comment]
![Screen Shot 2021-04-27 at 16 47 58](https://user-images.githubusercontent.com/7830949/116316968-53df7680-a778-11eb-9b42-03140badf948.png)
![Screen Shot 2021-04-27 at 16 48 56](https://user-images.githubusercontent.com/7830949/116317066-75d8f900-a778-11eb-80a4-c9a196430f66.png)
