### ISSUE TITLE
Collection Data Type Enumeration check breaks code with added value

### ISSUE THREAD

**Issue by andrewdweis** [NASA-IMPACT/pyQuARC#46]
**Describe the bug**
With the Collection/CollectionDataType element added

**To Reproduce**
1. Add "Collection/CollectionDataType" to the test_cmr_metadata.echo10 file with no value in field
2. Run python3 main.py --fake true
3. No Issue
4. Add any value to the Collection/CollectionDataType field, including the enumeration value of "SCIENCE_QUALITY"
5. See Error (main error: TypeError: controlled_keywords_check() takes 2 positional arguments but 4 were given)

**Expected behavior & Output**
Will give a true of false value whether or not the value in the Collection/CollectionDataType field is in the enumeration list
(https://git.earthdata.nasa.gov/projects/EMFD/repos/echo-schemas/browse/schemas/10.0/Collection.xsd#240)

**Comment by slesaad** [comment]
I cannot reproduce this. It's working fine for me. Wonder if previous commits solved this, can you check again @andrewdweis ?
