### ISSUE TITLE
Add Spatial Coverage Type Presence Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#49]
**Is this a new check? Please describe the check and the field.**
<Collection/SpatialInfo/SpatialCoverageType>: check that the field is provided.

**Describe the checks in steps**
1. Check that the field is provided.
2. If not, recommend providing a spatial coverage type from the following list: ["HORIZONTAL", "VERTICAL", "ORBITAL", "HORIZONTAL_VERTICAL", "ORBITAL_VERTICAL", "HORIZONTAL_ORBITAL", "HORIZONTAL_VERTICAL_ORBITAL"]

**Is there a similar check already implemented? Please list the name of the check**
data_center_name_presence_check

**Additional context**
Refer to Spatial Coverage Type Presence Check in the QA Rules spreadsheet.

**Comment by slesaad** [comment]
![Screen Shot 2021-05-04 at 15 04 14](https://user-images.githubusercontent.com/7830949/117063116-fef8ae80-ace9-11eb-84f7-47fc3e13136a.png)
addressed by: 3c69283
