### ISSUE TITLE
Add ECHO10 Spatial Coverage Type Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#50]
**Is this a new check? Please describe the check and the field.**
<Collection/Spatial/SpatialCoverageType> and <Collection/SpatialInfo/SpatialCoverageType>: check against controlled vocabulary list.

**Describe the checks in steps**
1. Check these fields against the following list: ["HORIZONTAL", "VERTICAL", "ORBITAL", "HORIZONTAL_VERTICAL", ORBITAL_VERTICAL", "HORIZONTAL_ORBITAL", "HORIZONTAL_VERTICAL_ORBITAL"]
2. If these fields don't comply with the list, provide a warning that the spatial coverage type provided does not match the controlled vocabulary.

**Is there a similar check already implemented? Please list the name of the check**
collection_data_type_enumeration_check

**Additional context**
Refer to ECHO10 Spatial Coverage Type Check in the QA Rules spreadsheet for more information.

**Comment by slesaad** [comment]
![Screen Shot 2021-04-29 at 14 23 27](https://user-images.githubusercontent.com/7830949/116606523-78f9f380-a8f6-11eb-8ddf-17b209bdadc9.png)

**Comment by slesaad** [comment]
addressed by: 690fbb7
