### ISSUE TITLE
Add Altitude Unit Controlled Vocabulary Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#51]
**Is this a new check? Please describe the check and the field.**
<Collection/SpatialInfo/VerticalCoordinateSystem/AltitudeSystemDefinition/DistanceUnits>: check against the altitude unit enumeration list from the UMM-C schema

**Describe the checks in steps**
1. Check the provided distance units against the following list: ["HectoPascals", "Kilometers", "Millibars"]
2. If it does not comply, provide a warning message stating that the provided distance units do not comply with the controlled vocabulary list.

**Is there a similar check already implemented? Please list the name of the check**
collection_data_type_enumeration_check

**Additional context**
Refer to Altitude Unit Controlled Vocabulary Check in the QA Rules spreadsheet for more information.

**Comment by slesaad** [comment]
![Screen Shot 2021-04-29 at 15 21 14](https://user-images.githubusercontent.com/7830949/116613646-8c10c180-a8fe-11eb-94dc-4e3a35e2ff0c.png)
fixed by: 1b6b016
