### ISSUE TITLE
Add Depth Unit Controlled Vocabulary

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#52]
**Is this a new check? Please describe the check and the field.**
<Collection/SpatialInfo/VerticalCoordinateSystem/DepthSystemDefinition/DistanceUnits>: check against the depth unit enumeration list from the UMM-C schema

**Describe the checks in steps**

1. Check the provided distance units against the following list: ["Fathoms", "Feet", "HectoPascals", "Meters", "Millibars"]
2. If it does not comply, provide a warning message stating that the provided distance units do not comply with the controlled vocabulary list.

**Is there a similar check already implemented? Please list the name of the check**
collection_data_type_enumeration_check

**Additional context**
Refer to Depth Unit Controlled Vocabulary Check in the QA Rules spreadsheet for more information.

**Comment by slesaad** [comment]
![Screen Shot 2021-04-29 at 15 05 13](https://user-images.githubusercontent.com/7830949/116611711-4e129e00-a8fc-11eb-9445-dab3b6f7f846.png)

Addressed by: c51869a
