### ISSUE TITLE
Add Horizontal Datum Name Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#53]
**Is this a new check? Please describe the check and the field.**
<Collection/SpatialInfo/HorizontalCoordinateSystem/GeodeticModel/HorizontalDatumName>: check to see if a horizontal datum name is provided.

**Describe the checks in steps**
1. Check to see if a horizontal datum name is provided.
2. If not, recommend providing a horizontal datum name.

**Is there a similar check already implemented? Please list the name of the check**
ECHO10 Data Center Name Presence Check

**Additional context**
Refer to the Horizontal Datum Name Check in the QA Rules spreadsheet for more information.

**Comment by slesaad** [comment]
![Screen Shot 2021-05-04 at 16 44 22](https://user-images.githubusercontent.com/7830949/117073758-fc04ba80-acf7-11eb-89d2-d4ea6f8ab05b.png)
addressed by: 90a8688
