### ISSUE TITLE
Add Validate Beginning Date Time Against Granules Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#55]
**Is this a new check? Please describe the check and the field.**
<Collection/Temporal/RangeDateTime/BeginningDateTime>: check whether the beginning date time matches the beginning date time of the first granule in the collection (if granules exist.)

**Describe the checks in steps**
1. Check whether the Beginning Date Time matches the granule metadata.
2. If the granule temporal metadata does not match, provide a message stating "There is a discrepency between the beginning date time and the start time of the first granule in the collection."

**Is there a similar check already implemented? Please list the name of the check**

**Additional context**
Note: if only a date is provided (rather than a dateTime), then only the date needs to be compared. Refer to "Validate Beginning Date Time Against Granules" in the QA Rules spreadsheet for more information.

**Comment by slesaad** [comment]
Addressed by: 298ab54
