### ISSUE TITLE
Add ECHO10 OPeNDAP URL Location Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#59]
**Is this a new check? Please describe the check and the field.**
<Collection/OnlineAccessURLs/OnlineAccessURL/URL>: check to make sure that an OPeNDAP access URL is not provided in the Online Access URL field.

**Describe the checks in steps**
1. Check to make sure that an OPeNDAP access URL is not provided in the Online Access URL field.
2. If an OPeNDAP access URL is provided in this field, recommend moving it to the OnlineResourceURL/URL field.

**Is there a similar check already implemented? Please list the name of the check**

**Additional context**
Refer to the ECHO10 OPeNDAP URL Location Check in the QA Rules spreadsheet for more information.

**Comment by slesaad** [comment]
![Screen Shot 2021-05-10 at 09 51 15](https://user-images.githubusercontent.com/7830949/117678719-444b2f00-b175-11eb-8ac5-0fde2c02efae.png)
Addressed by: e6ae62e
