### ISSUE TITLE
Add Spatial Extent Requirement Fulfillment Check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#63]
**Is this a new check? Please describe the check and the field.**
Check that the spatial extent requirement is satisfied. At least one of the following fields should be provided:
Collection/Spatial/HorizontalSpatialDomain/Geometry/Point/PointLongitude
Collection/Spatial/HorizontalSpatialDomain/Geometry/Point/PointLatitude
Collection/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle/WestBoundingCoordinate
Collection/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle/EastBoundingCoordinate
Collection/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle/SouthBoundingCoordinate
Collection/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle/NorthBoundingCoordinate
Collection/Spatial/HorizontalSpatialDomain/Geometry/GPolygon/Boundary/Point/PointLongitude
Collection/Spatial/HorizontalSpatialDomain/Geometry/GPolygon/Boundary/Point/PointLatitude
Collection/Spatial/HorizontalSpatialDomain/Geometry/Line/Point/PointLongitude
Collection/Spatial/HorizontalSpatialDomain/Geometry/Line/Point/PointLatitude

**Describe the checks in steps**
1. Check that at least one of the above fields is provided.
2. If none are provided, recommend providing a spatial extent in one of the following forms:
a. Point
b. Bounding Rectangle
c. GPolygon
d. Line

**Is there a similar check already implemented? Please list the name of the check**
Temporal Extent Requirement Check

**Additional context**
Refer to the Spatial Extent Requirement Fulfillment Check in the QA Rules spreadsheet for more informaiton.

**Comment by slesaad** [comment]
![Screen Shot 2021-05-10 at 11 14 27](https://user-images.githubusercontent.com/7830949/117690838-e45a8580-b180-11eb-9d0f-32df5098d5fe.png)
Addressed by: 184cb3f
