### ISSUE TITLE
Code breaks If Collection/DeleteTime is not in ISO Format

### ISSUE THREAD

**Issue by andrewdweis** [NASA-IMPACT/pyQuARC#64]
**Describe the bug**
In the Collection/DeleteTime field the following occurs:
- If field is populated with an appropriate DateTime in ISO Format - the program returns true in the Datetime Format Check
- if field is populated with nothing - the program does not apply the Datetime Format Check
- If field includes anything other than a complete Datetime ISO format value - the program breaks with the errors:

"File "/Users/aweis/Desktop/ARC/revamped_pycmr-refactor-polish_code/code/datetime_validator.py", line 76, in delete_time_check
    delete_time.replace(
AttributeError: 'bool' object has no attribute 'replace'"

**To Reproduce**
1. Add the Collection/DeleteTime to the test_cmr_metadata.echo10 record
2. Include any value other than a complete Datetime in ISO format
3. Run python3 main.py --fake true

**Expected behavior**
If the metadata includes any value other than ISO format it should produce an error message with a FALSE result

**Comment by slesaad** [comment]
I cannot reproduce this. 
I tried all three cases and it works as expected.
Can you check again @andrewdweis ?
