### ISSUE TITLE
Add URL Description Check

### ISSUE THREAD

**Issue by andrewdweis** [NASA-IMPACT/pyQuARC#65]
**Is this a new check? Please describe the check and the field.**
Create a URL Description Check for the following fields
- Collection/OnlineAccessURLs/OnlineAccessURL/URLDescription
- Collection/OnlineResources/OnlineResource/Description

**Describe the checks in steps**
The Description is optional for these two fields but is highly recommended. We would like a check to be implemented that warns when there is not a description in either of these fields. Also, if there are multiple URL descriptions in place, we'd like to check and make sure that all descriptions are unique.

**Comment by slesaad** [comment]
![Screen Shot 2021-05-10 at 09 29 48](https://user-images.githubusercontent.com/7830949/117675535-452e9180-b172-11eb-8f65-dc4fbc9d1ea5.png)
![Screen Shot 2021-05-10 at 09 29 57](https://user-images.githubusercontent.com/7830949/117675565-49f34580-b172-11eb-8d01-dacf6fbab43f.png)

**Comment by slesaad** [comment]
Addressed by: bedd5ca
