### ISSUE TITLE
Add Characteristic Name Uniqueness Check

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#69]
**Is this a new check? Please describe the check and the field.**
<Collection/Platforms/Platform/Characteristics/Characteristic/Name>: if multiple characteristics are provided for one platform, check to ensure that the provided name is unique.

**Describe the checks in steps**
1. Check to make sure the characteristic names are unique.
2. If not, recommend providing a unique name for each characteristic.

**Is there a similar check already implemented? Please list the name of the check**

**Additional context**

**Comment by svbagwell** [comment]
Hi Slesa! When two or more identical platform characteristic names are provided, pyQuARC isn't flagging it as an error. It doesn't seem like the check is present.
