### ISSUE TITLE
Add User Services Check under Contact Person fields

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#70]
**Is this a new check? Please describe the check and the field.**
Sometimes the following fields will be populated as follows:
Collection/Contacts/Contact/ContactPersons/ContactPerson/FirstName: "User"
Collection/Contacts/Contact/ContactPersons/ContactPerson/MiddleName: "null"
Collection/Contacts/Contact/ContactPersons/ContactPerson/LastName: "Services"

We're requesting a check to make sure that the fields are not populated this way.

**Describe the checks in steps**
1. Check First Name, Middle Name, and Last Name for entries 'User', 'null', and 'Services' respectively.
2. If they are populated this way, recommend removing from the metadata and consider placing "User Services" in the Organization Name field.

**Is there a similar check already implemented? Please list the name of the check**

**Additional context**

**Comment by andrewdweis** [comment]
Hi Slesa! In the event that only First Name and Last Name are populated this test seems to pass; however in the following example below, the same error is not thrown that would be expected.

```
            <Contact>
                  <Role>ARCHIVER</Role>
                  <ContactPersons>
                        <ContactPerson>
                              <FirstName>User</FirstName>
                              <MiddleName>null</MiddleName>
                              <LastName>Services</LastName>
                              <JobPosition>METADATA AUTHOR</JobPosition>
                        </ContactPerson>
                  </ContactPersons>
            </Contact>
```

Thanks and let me know if you have any questions!

**Comment by slesaad** [comment]
Tested this, seems like it's working already
