### ISSUE TITLE
Add a boolean check

### ISSUE THREAD

**Issue by jmw0057** [NASA-IMPACT/pyQuARC#72]
**Is this a new check? Please describe the check and the field.**
The following fields should be populated as "true" or "false":
Collection/Orderable
Collection/Visible

Requesting a check to make sure they are populated as either "true" or "false".

**Describe the checks in steps**
1. Check to make sure these fields are populated as either "true" or "false".
2. If not, provide a statement that the field is a boolean field and requires an entry of "true" or "false".

**Is there a similar check already implemented? Please list the name of the check**

**Additional context**

**Comment by slesaad** [comment]
![Screen Shot 2021-05-11 at 09 35 11](https://user-images.githubusercontent.com/7830949/117833707-301e3500-b23c-11eb-95ff-5fe3eb2fb3aa.png)
addressed by: 013de23
