### ISSUE TITLE
Add License Information Check

### ISSUE THREAD

**Issue by spmcneal** [NASA-IMPACT/pyQuARC#75]
**Is this a new check? Please describe the check and the field.**
<Collection/UseConstraints>: checks whether license information is provided in the metadata..

**Describe the checks in steps**

1. For the "Collection/UseConstraints" field, checks whether license information is provided (can be either a link to license info or free text in the ECHO10 format).

2. If not, provide a warning message stating: No license information provided. Recommend providing information about the 
    license applicable to the dataset, preferably as a URL. For EOSDIS records, recommend providing the following link (unless 
    under different usage terms): https://earthdata.nasa.gov/earth-observation-data/data-use-policy 

**Is there a similar check already implemented? Please list the name of the check**

**Additional context**
Refer to the "License Information Check" in the QA Rules spreadsheet for more information.

**Comment by andrewdweis** [comment]
Hi Slesa! While free text is allowed for this field, we'd like to add that this checks that the value of _UseConstraints_ is not an empty string and provides the same warning as above.

Thanks and let me know if you have any questions!
