### ISSUE TITLE
Location GCMD Checks

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#86]
**Describe the bug**
The GCMD checks for the following DIF10 fields appear to be missing:
Location_Category
Location_Type
Location_Subregion1
Location_Subregion2
Location_Subregion3

**To Reproduce**
1. Go to the test_cmr_metadata.dif10 file
2. Modify the fields listed above so that they are populated with random characters (e.g. <Location_Category>jkfdpoan</Location_Category>)
3. Run py main.py --fake FAKE --format dif10
4. See that no error is provided

**Expected behavior**
Expected to see an Error message stating that the location keyword provided does not comply with GCMD.

**Comment by spa0002** [comment]
"Runs as expected
Hierarchy is checked"
