### ISSUE TITLE
DIF10: Dif10 Complex Types do not need to be in schema order

### ISSUE THREAD

**Issue by andrewdweis** [NASA-IMPACT/pyQuARC#87]
**Describe the bug**
Through testing of multiple complex types in the schema, the schema produces errors if the elements in the same hierarchy differ from the exact order in the dif10 schema. This should not be the case - elements in the same complex type can be in any order

**To Reproduce**
NOTE: The Dif10 Schema Order for Spatial_Coverage is [Spatial_Coverage_Type, Granule_Spatial_Representation, Zone_Identifier, Geometry, Orbit_Parameters, Vertical_Spatial_Info, Spatial_Info]

Change Spatial_Coverage to the following in FAKE file and see error below [Note: Zone_Identifier is at the end rather than after Granule_Spatial_Representation]

<Spatial_Coverage>
    <Spatial_Coverage_Type>Horizontal</Spatial_Coverage_Type>
    <Granule_Spatial_Representation>GEODETIC</Granule_Spatial_Representation>
    <Geometry>
      <Coordinate_System>CARTESIAN</Coordinate_System>
      <Bounding_Rectangle>
        <Southernmost_Latitude>-90</Southernmost_Latitude>
        <Northernmost_Latitude>90</Northernmost_Latitude>
        <Westernmost_Longitude>-180</Westernmost_Longitude>
        <Easternmost_Longitude>180</Easternmost_Longitude>
      </Bounding_Rectangle>
    </Geometry>
    <Spatial_Info>
      <Spatial_Coverage_Type>TEST</Spatial_Coverage_Type>
      <Horizontal_Coordinate_System>
        <Geodetic_Model>
          <Horizontal_DatumName>TEST</Horizontal_DatumName>
        </Geodetic_Model>
      </Horizontal_Coordinate_System>
    </Spatial_Info>
    <Zone_Identifier>TEST</Zone_Identifier>
  </Spatial_Coverage>

**Expected behavior**
The above metadata portion should pass with No Errors

**Outputs**
Receiving this error:

(pyQuARC) aweis@Weis-Impact pyQuARC % python main.py --fake FAKE --format dif10       

        ********************************
        ** Metadata Validation Errors **
        ********************************

	METADATA: /Users/aweis/Desktop/ARC/pyQuARC/pyQuARC-feature-dif_support/pyQuARC/../tests/fixtures/test_cmr_metadata.dif10

	>> Zone_Identifier: 
		Error: This element is not expected.

**Additional context**
This is an example for one instance - the order for any Metadata Complex Type should not matter. Please reach out for clarification

**Comment by spa0002** [comment]
**To Reproduce**
```
  <Spatial_Coverage>
    <Spatial_Coverage_Type>Horizontal</Spatial_Coverage_Type>
    <Granule_Spatial_Representation>GEODETIC</Granule_Spatial_Representation>
    <Geometry>
      <Coordinate_System>CARTESIAN</Coordinate_System>
      <Bounding_Rectangle>
        <Southernmost_Latitude>-90</Southernmost_Latitude>
        <Northernmost_Latitude>90</Northernmost_Latitude>
        <Westernmost_Longitude>-180</Westernmost_Longitude>
        <Easternmost_Longitude>180</Easternmost_Longitude>
      </Bounding_Rectangle>
    </Geometry>
    <Spatial_Info>
      <Spatial_Coverage_Type>TEST</Spatial_Coverage_Type>
      <Horizontal_Coordinate_System>
        <Geodetic_Model>
          <Horizontal_DatumName>TEST</Horizontal_DatumName>
        </Geodetic_Model>
      </Horizontal_Coordinate_System>
    </Spatial_Info>
    <Zone_Identifier>TEST</Zone_Identifier>
  </Spatial_Coverage>

```
