### ISSUE TITLE
DIF10: Add Platform Short Name GCMD Check

### ISSUE THREAD

**Issue by jenny-m-wood** [NASA-IMPACT/pyQuARC#88]
**Is this a new check? Please describe the check and the field.**
</DIF/Platform/Short_Name>: check against the GCMD Platform list

**Describe the checks in steps**
1. Verify that the Platform Short Name provided is included in the GCMD Platform list
2. If the platform short name does not exist in the GCMD list, provide an error that states: "The provided Platform Short Name does not comply with GCMD."

**Is there a similar check already implemented? Please list the name of the check**
Platform Long Name GCMD Check

**Comment by spa0002** [comment]
Check added and worked as expected when tested.
